linters:
  disable-all: true
  enable:
    - gofmt
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - wastedassign
linters-settings:
  gosec:
    excludes:
      - G404
