# Try the release flow to ensure it works
# Keep in sync with release.yml

name: Try release
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  try-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./build-release.sh
