# Try the release flow to ensure it works
# Keep in sync with release.yml

name: Try release
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  try-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./build-release.sh
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          path: "build/*.zip"
          if-no-files-found: error
