# Try the release flow to ensure it works
# Keep in sync with release.yml

name: Try release
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  try-release:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24.2
      - run: ./build-release.sh
